services:
  - type: web
    name: shared-realtime-document
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DOC_PASSWORD
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_BASE64
        sync: false
      - key: FIRESTORE_DATABASE_ID
        value: musical
